[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_REACT_APP_NEWS_API_KEY = "d5a7e037301940f09b7a491fe4dadf37" # Replace with your actual API key
  VITE_REACT_APP_BASE_URL = "https://your-api-base-url.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
